import { Art } from './Typings';

/**
 * The list of breathing styles.
 */
const breathingStyles: Art[] = [
  {
    id: 'beast',
    name: 'Souffle de la Bête',
    moves: [
      'Premier Croc : Perforation',
      'Deuxième Croc : Lacération',
      'Troisième Croc : Déchiquetage',
      'Quatrième Croc : Dilacération',
      'Cinquième Croc : Mutilation Furieuse',
      'Sixième Croc : Morsure Irrégulière',
      'Septième Croc : Détection',
      'Huitième Croc : Charge du Sanglier',
      'Neuvième Croc : Taillade Ondulante Divine',
      'Dixième Croc : Les Crocs Tournoyants',
      'La Frappe Lancée',
    ],
    movesCategories: {
      basic: [0, 1, 2, 6],
      fineness: [3, 5, 10],
      heavy: [4, 8, 9],
      ultimate: [7],
    },
  },
  {
    id: 'flame',
    name: 'Souffle de la Flamme',
    moves: [
      'Premier Mouvement : Mer de Flammes',
      'Deuxième Mouvement : Flammes du Soleil Ascendant',
      'Troisième Mouvement : Univers de Flammes',
      'Quatrième Mouvement : La Vague Flamboyante',
      'Cinquième Mouvement : Tigre de Flammes',
      'Neuvième mouvement : Purgatoire',
    ],
    movesCategories: {
      basic: [1, 2],
      fineness: [0],
      heavy: [3],
      ultimate: [4, 5],
    },
  },
  {
    id: 'flower',
    name: 'Souffle de la Fleur',
    moves: [
      'Deuxième Mouvement : Esprit du Prunier',
      'Quatrième Mouvement : Hanagoromo Pourpre',
      'Cinquième Mouvement : La Pivoine Futile',
      'Sixième Mouvement : Tourbillon de Pêche',
      'Mouvement Final : Les Yeux du Lycoris',
    ],
    movesCategories: {
      basic: [0, 1],
      fineness: [3],
      heavy: [2],
      ultimate: [4],
    },
  },
  {
    id: 'insect',
    name: "Souffle de l'Insecte",
    moves: [
      'Danse des Papillons : Papillonnage',
      "Danse de la Piqûre d'Abeille : Battement Véritable",
      'Danse de la Libellule : Œil à Facettes Hexagonales',
      'Danse du Myriapode : Zigzag Centipède',
    ],
    movesCategories: {
      basic: [0],
      fineness: [1],
      heavy: [2],
      ultimate: [3],
    },
  },
  {
    id: 'love',
    name: "Souffle de l'Amour",
    moves: [
      'Premier Mouvement : Les Frissons du Premier Amour',
      'Deuxième Mouvement : Amour Anxiogène',
      'Troisième Mouvement : Toilette de Chaton Mignon',
      'Cinquième Mouvement : Attachement Hésitant, Ongles Mal Vernis',
      'Sixième Mouvement : Un Amour de Patte de Chaton',
    ],
    movesCategories: {
      basic: [0, 1],
      fineness: [4],
      heavy: [2],
      ultimate: [3],
    },
  },
  {
    id: 'mist',
    name: 'Souffle de la Brume',
    moves: [
      'Premier Mouvement : Brume Suspendu dans le Ciel',
      'Deuxième Mouvement : Multiples Nappes de Brouillards',
      'Troisième mouvement : Éclaboussures de Brume',
      "Quatrième Mouvement : Frappe d'Advection",
      'Cinquième Mouvement : Océan de Brouillard',
      'Sixième Mouvement : Brouillard au Clair de Lune',
      'Septième Mouvement : Voile de Brume',
    ],
    movesCategories: {
      basic: [0, 1],
      fineness: [3, 5],
      heavy: [4, 6],
      ultimate: [7],
    },
  },
  {
    id: 'moon',
    name: 'Souffle de la Lune',
    moves: [
      'Premier Mouvement : Lune Obscure, Palais Vespéral',
      'Deuxième Mouvement : Contemplation des Fleurs de Lune',
      'Troisième Mouvement : Lune de Haine, Chaîne Destructrice',
      "Cinquième Mouvement : Vortex Maudit de l'Esprit Lunaire",
      "Sixième Mouvement : Lune Solitaire dans la Nuit Perpétuelle, L'Avīci",
      'Septième Mouvement : Miroir Maléfique, Sublimation Lunaire',
      'Huitième Mouvement : Ouroboros Lunaire',
      'Neuvième Mouvement : Salve de Lunes Gibbeuses Décroissantes',
      'Dixième Mouvement : Rayons de Lune Perforant le Feuillage',
      'Quatorzième Mouvement : Cataclysme, Ciel de Lunes Croissantes',
      'Seizième Mouvement : Arc-en-Ciel Lunaire, Demi-Lune',
    ],
    movesCategories: {
      basic: [0, 6, 8],
      fineness: [1, 3, 5],
      heavy: [2, 4, 7],
      ultimate: [9, 10],
    },
  },
  {
    id: 'serpent',
    name: 'Souffle du Serpent',
    moves: [
      'Premier Mouvement : Frappe du Serpent Recroquevillé',
      'Deuxième Mouvement : Le Crochet Empoisonné du Petit Serpent',
      'Troisième Mouvement : Constriction',
      'Quatrième Mouvement : Serpent Bicéphale',
      'Cinquième Mouvement : Ondulations du Serpent',
    ],
    movesCategories: {
      basic: [0, 3],
      fineness: [1],
      heavy: [2],
      ultimate: [4],
    },
  },
  {
    id: 'sound',
    name: 'Souffle du Son',
    moves: [
      'Premier Mouvement : Tonnerre',
      "Quatrième Mouvement : Le Glas Mortel de L'Avīci",
      'Cinquième Mouvement : Symphonie Stridente',
    ],
    movesCategories: {
      basic: [0],
      fineness: [1],
      heavy: [1],
      ultimate: [2],
    },
  },
  {
    id: 'stone',
    name: 'Souffle de la Roche',
    moves: [
      'Premier Mouvement : Serpentinite, Tenaille Polarisée',
      'Deuxième Mouvement : Fracassement de la Voûte Céleste',
      'Troisième Mouvement : Peau de Pierre',
      'Quatrième Mouvement : Rhyolite, Conquête Rapide',
      'Cinquième Mouvement : La Roue de Pierre de la Justice',
    ],
    movesCategories: {
      basic: [1],
      fineness: [2],
      heavy: [0, 3],
      ultimate: [4],
    },
  },
  {
    id: 'sun',
    name: 'Souffle du Soleil',
    moves: [
      'Valse',
      'Valse Foudroyante',
      'Paradis Bleu',
      'Miroir Brûlant Écarlate',
      'Arc-en-Ciel Parhélique',
      'Char Enflammé',
      'Le Soleil qui Réduit les Os en Cendres',
      'Estoc Brillant du Soleil',
      'Chaleur Ondulante',
      'Le Coucher de Soleil',
      'Rai de Lumière',
      'Halo Solaire Danse Draconique',
      'Valse Enflammée',
      'Treizième Mouvement',
    ],
    movesCategories: {
      basic: [0, 1, 7, 8],
      fineness: [2, 3, 4, 6, 12],
      heavy: [5, 9, 10],
      ultimate: [11, 13],
    },
  },
  {
    id: 'thunder',
    name: 'Souffle de la Foudre',
    moves: [
      'Premier Mouvement : Frappe Foudroyante',
      'Premier Mouvement : Frappe Foudroyante - Six Coups',
      'Premier Mouvement : Frappe Foudroyante - Huit Coups',
      'Premier Mouvement : Frappe Foudroyante - vitesse Divine',
      'Deuxième Mouvement :  me de Foudre',
      'Troisième Mouvement : Essaim Électrique',
      'Quatrième Mouvement : Tonnerre Lointain',
      'Cinquième Mouvement : Orage Brûlant',
      'Sixième Mouvement : Éclairs Grondants',
      'Septième mouvement : Dieu des Éclairs de Feu',
    ],
    movesCategories: {
      basic: [0, 1, 2],
      fineness: [3, 6],
      heavy: [4, 5, 7, 8],
      ultimate: [9],
    },
  },
  {
    id: 'water',
    name: "Souffle de l'Eau",
    moves: [
      "Premier Mouvement : Entaille de l'Eau Calme",
      "Deuxième Mouvement : La Roue d'Eau",
      "Deuxième Mouvement : La Roue d'Eau - Variation Horizontale",
      'Troisième Mouvement : Danse des Courants',
      'Quatrième Mouvement : La Marée Déferlante',
      'Cinquième Mouvement : Averse Providentielle',
      'Sixième Mouvement : Tourbillon',
      'Sixième et Troisième Mouvement Combinés : Tourbillon Dansant',
      "Septième Mouvement : Goutte de Rosée Troublant l'Eau Dormante",
      "Septième Mouvement : Goutte de Rosée Troublant l'Eau Dormante - En Crochet",
      'Huitième Mouvement : Impact de la Cascade',
      'Neuvième Mouvement : Embruns des Flots Déchaînés',
      'Dixième Mouvement : Les Vicissitudes de la Vie',
      'Onzième Mouvement : Accalmie',
    ],
    movesCategories: {
      basic: [0, 1, 5, 8],
      fineness: [2, 6, 9, 10],
      heavy: [3, 4, 7, 11],
      ultimate: [12, 13],
    },
  },
  {
    id: 'wind',
    name: 'Souffle du Vent',
    moves: [
      'Premier Mouvement : Tourbillon de Poussière - Tranche',
      'Deuxième Mouvement : Griffes de Vent Purificatrices',
      'Troisième Mouvement : Arbre Ondulant dans la Brise Montagnarde',
      'Quatrième Mouvement : La Tempête de Poussière Levant',
      'Cinquième Mouvement : Tempête Hivernale',
      'Sixième Mouvement : La Rafale de Fumée Noire',
      'Septième Mouvement : Vent Puissant - Bourrasque de Tengu',
      'Huitième Mouvement : Frappe de la Première Bourrasque',
      'Neuvième Mouvement : Typhon de Skanda',
    ],
    movesCategories: {
      basic: [0, 3, 7],
      fineness: [1, 4, 5],
      heavy: [2, 6],
      ultimate: [8],
    },
  },
];

export default breathingStyles;
